export const CREATE_LINK_IN_PROGRESS = 'CREATE_LINK_IN_PROGRESS';
export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS';
export const CREATE_LINK_FAIL = 'CREATE_LINK_FAIL';
export const DELETE_ALL_LINKS = 'DELETE_ALL_LINKS';
export const REFRESH_All_LINKS_INFO = 'REFRESH_All_LINKS_INFO';
