export const CREATE_LINK_REQUEST = 'CREATE_LINK_REQUEST';
export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS';
export const CREATE_LINK_FAIL = 'CREATE_LINK_FAIL';

export const LINK_INFO_REQUEST = 'LINK_INFO_REQUEST';
export const LINK_INFO_SUCCESS = 'LINK_INFO_SUCCESS';
export const LINK_INFO_FAIL = 'LINK_INFO_FAIL';

export const DELETE_ALL_LINKS = 'DELETE_ALL_LINKS';
